api/urls.py
# -*- coding: utf-8 -*-
"""
URL config for the lmapi module.
"""
from django.conf.urls import include, url
from rest_framework import routers

from . import viewsets

router = routers.DefaultRouter()  # pylint: disable=invalid-name
router.register(r'commits', viewsets.CommitViewSet)
router.register(r'files', viewsets.FilesViewSet)

urlpatterns = [  # pylint: disable=invalid-name
    url(r'^', include(router.urls)),
]

wvcs/urls.py
"""
wvcs URL Configuration
"""
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import include, url

from core import views
from frontend.views import app

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^upload', views.commit_form),
    url(r'^files', views.files_list),
    url(r'^repo', views.repo_state),
    url(r'^app', app),
    url('^api/', include('api.urls')),
    url(r'^$', views.commits_list),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
"""
Model definitions for WVCS.
"""
from django.db import models, transaction

from core import models as core_models
from core import tools


class WVCSModelBase(models.Model):
    """
    Abstract base model for all WVCS models.
    """
    create_stamp = models.DateTimeField(auto_now_add=True)
    modify_stamp = models.DateTimeField(auto_now=True, help_text='This updates whenever modifications are saved.')

    class Meta(object):
        abstract = True


class CommitQuerySet(models.QuerySet):
    """
    Overload create to ensure it always happens the right way.
    """

    def create(self, message: str, files: list):
        # We don't want any files to make it through unless they all do
        with transaction.atomic():
            # Now create commit to mark the project file change.
            commit = Commit(message=message)
            commit.save()

            # Create Files for each file.
            # Still a bit muddly. Reconsider this relationship.
            for file in files:
                core_models.File.objects.create(
                    commit=commit,
                    file_pointer=file,
                    file_hash=tools.file_hash(file.read()),
                    name=file.name)
        return commit


class Commit(WVCSModelBase):
    """
    Represents a change in project files.
    """
    message = models.TextField(help_text='A useful description of the commit.')
    objects = CommitQuerySet.as_manager()

    def __str__(self):
        return self.message


class File(WVCSModelBase):
    """
    Contains metadata for an individual file, and the file object itself. 
    """
    file_pointer = models.FileField(upload_to='uploads/%Y/%m/%d/', help_text='An uploaded file.')
    file_hash = models.TextField(help_text="The SHA1 hash of this file's contents.", max_length=40)
    name = models.TextField(help_text='The given filename. Will be used to attempt to track file versions.')
    commit = models.ForeignKey(Commit, help_text='Which commits this file appears in.', related_name='files')

    def __str__(self):
        return '{}: {}'.format(self.name, self.file_hash)

core/views.py
"""
Simple views to handle file uploads and displaying data.
"""

from django.db.models import Max
from django.shortcuts import redirect, render

from core import models


def commits_list(request):
    """
    Lists commits in time order ascending
    """
    return render(request, 'core/commits_list.html', context={
        'commits': models.Commit.objects.order_by('-create_stamp'),
    })


def files_list(request):
    """
    Lists files.
    """
    return render(request, 'core/files_list.html', context={
        'files_by_name': models.File.objects.order_by('name'),
        'files_by_hash': models.File.objects.order_by('hash', 'create_stamp'),
    })


def repo_state(request):
    """
    Shows the current state of the repo / branch / whatever we're calling it.
    Massive hack since SQLite doesn't allow `DISTINCT ON`.
    """
    # Group Files by name, and annotate the highest ID to each group.
    # Then get a list of the IDs
    latest_file_ids = models.File.objects.values('name').annotate(
        id__max=Max('id')).values_list('id__max', flat=True)

    # Hit the DB again and get these files.
    current_files = models.File.objects.filter(pk__in=latest_file_ids).order_by('name')
    return render(
        request, 'core/repo.html', context={'files': current_files})


def commit_form(request):
    """
    Simple view function to handle file uploads.
    """
    if request.method == 'POST':
        models.Commit.objects.create(message=request.POST['message'], files=request.FILES.getlist('files'))
        return redirect('/repo')

    # Show template
    return render(request, 'core/commit_form.html')

frontend/views.py
"""
One-hit wonder.
"""
from django.shortcuts import render


def app(request):
    """
    The root view for the WVCS frontend.
    """
    return render(request, 'build/index.html')

core/templates/core/base.html
{% load static %}

<html>
<head>
    <link rel="stylesheet" href="{% static 'normalize.css' %}">
    <link rel="stylesheet" href="{% static 'skeleton.css' %}">
    <style>
        body {
            padding: 20px;
        }

        nav {
            text-align: right;
        }

        dd, dt {
            float: left
        }

        dd {
            width: 70%;
            clear: right;
        }

        dt {
            width: 20%;
            clear: left;
        }
        dl {
            overflow: auto;
        }
    </style>
</head>
<main>
    <nav>
        <a href="/repo">Repo</a> |
        <a href="/files">File history</a> |
        <a href="/">Commits</a> |
        <a href="/uploads">Add commit</a>
    </nav>
    {% block content %}{% endblock %}
</main>
</html>

core/templates/core/commit_form.html
{% extends 'core/base.html' %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>
        <label for="id_message">Message:</label>
        <input type="text" name="message" required="" id="id_message"></p>
        <label for="id_files">Files:</label>
        <input type="file" name="files" multiple="" required="" id="id_files"></p>
    <input type="submit" value="Upload files">
</form>
{% endblock %}

core/templates/core/commits_list.html
{% extends 'core/base.html' %}
{% block content %}
    <h2>Commits:</h2>

    {% for commit in commits %}
        <dl>
            <dt>Message</dt>
            <dd>{{ commit.message }}</dd>
            <dt>Commit ID</dt>
            <dd><b>{{ commit.id }}</b></dd>
            <dt>Time</dt>
            <dd>{{ commit.create_stamp }}</dd>
            <dt>Files added</dt>
            <dd>
                {% for file in commit.files.all %}{{ file.name }} <code>{{ file.hash }}</code><br>{% endfor %}
            </dd>
        </dl>
        <hr>
    {% endfor %}

{% endblock %}

core/templates/core/files_list.html
{% extends 'core/base.html' %}
{% block content %}
    <h2>File history</h2>
    {% regroup files_by_name by name as files_grouped_by_name %}
    <h4>Versions by commit</h4>
    {% for name, file_list in files_grouped_by_name %}
        <h5>{{ name }}</h5>

        {% for file in file_list %}
            <dl>
                <dt>Commit ID</dt>
                <dd><code>{{ file.commit.id }}</code></dd>
                <dt>Time</dt>
                <dd>{{ file.commit.create_stamp }}</dd>
                <dt>Size</dt>
                <dd>{{ file.file_pointer.file.size|filesizeformat }} ({{ file.file_pointer.file.size }} B)</dd>
            </dl>
            <hr>
        {% endfor %}
    {% endfor %}

    <h4>Versions by file content</h4>
    {% for name, file_list in files_grouped_by_name %}
        <h5>{{ name }}</h5>
        {% regroup file_list by hash as files_grouped_by_hash %}
        {% for hash, hash_file_list in files_grouped_by_hash %}
            <dl>
                <dt>File hash</dt>
                <dd><code>{{ hash_file_list.0.hash }}</code></dd>
                <dt>Time</dt>
                <dd>{{ hash_file_list.0.commit.create_stamp }}</dd>
                <dt>Size</dt>
                <dd>{{ hash_file_list.0.file_pointer.file.size|filesizeformat }} ({{ hash_file_list.0.file_pointer.file.size }} B)</dd>
            </dl>
        {% endfor %}
    {% endfor %}
{% endblock %}

core/templates/core/repo.html
{% extends 'core/base.html' %}
{% block content %}
    <h2>Repo:</h2>

    {% for file in files %}
        <dl>
            <dt>Name</dt>
            <dd>{{ file.name }}</dd>
            <dt>File hash</dt>
            <dd><code>{{ file.hash }}</code></dd>
            <dt>Added in commit</dt>
            <dd>{{ file.commit.id }}</dd>
            <dt>Time</dt>
            <dd>{{ file.commit.create_stamp }}</dd>
            <dt>Size</dt>
            <dd>{{ file.file_pointer.file.size|filesizeformat }} ({{ file.file_pointer.file.size }} B)</dd>
        </dl>
        <hr>
    {% endfor %}

{% endblock %}